name: Copilot Prompt Automation

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt to send to Copilot"
        required: true
      issue_number:
        description: "Issue number (optional if your script uses it)"
        required: false

jobs:
  run-copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install requests

      - name: Run Copilot automation
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          PROMPT: ${{ inputs.prompt }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
        run: |
          python3 scripts/copilot_action.py
